Algoritmo "circulo"

// Disciplina: Algoritmos
// Professor: Conrado Salomé Ribeiro
// Descrição: Descreva o que o algoritmo faz
// Autor(a): Nome do(a) aluno(a)
// Data: 12/03/2026

Var
// Seção de Declarações das variáveis
 r, area : real

Inicio
// Seção de Comandos
 escreva ("Digite o valor do raio do circulo: ")
 leia (r)
 escreval (r)
 
 area <- 3.14159 * r * r
 
 escreva ("AREA = ", area:8:3)


fimalgoritmo