Algoritmo "consumo"

// Disciplina: Algoritmos
// Professor: Conrado Salomé Ribeiro
// Descrição: Descreva o que o algoritmo faz
// Autor(a): Nome do(a) aluno(a)
// Data: 12/03/2026

Var
// Seção de Declarações das variáveis
 dp : inteiro
 cg, cm: real
 

Inicio
// Seção de Comandos
 escreva ("Distancia percorrida: ")
 leia (dp)
 escreval (dp)
 
 escreva ("Combustivel gasto: ")
 leia (cg)
 escreval (cg)
 
 cm <- dp / cg
 
 escreva ("Consumo medio = ", cm:0:3)

fimalgoritmo