Algoritmo "pagamento"

// Disciplina: Logica da programacao
// Autor(a): Daniel Pedroso
// Data: 12/03/2026

Var
// Seção de Declarações das variáveis
 n : caractere
 vh, p: real
 ht: inteiro

Inicio
// Seção de Comandos
 escreva ("Nome: ")
 leia (n)
 escreval (n)
 
 escreva ("Valor da hora: ")
 leia (vh)
 escreval (vh:0:2)
 
 escreva ("Horas trabalhada: ")
 leia (ht)
 escreval (ht)
 
 p <- ht * vh
 
 escreva ("O pagamento para ", n, " deve ser ", p:0:2)
 


fimalgoritmo
