Algoritmo "soma"

// Disciplina: Algoritmos
// Professor: Conrado Salomé Ribeiro
// Descrição: Descreva o que o algoritmo faz
// Autor(a): Nome do(a) aluno(a)
// Data: 11/03/2026

Var
  // Seção de Declarações das variáveis
  x, y : inteiro
  soma : real

Inicio
  // Seção de Comandos
  escreva ("Digite o valor X: ")
  leia (x)
  escreval (x)

  escreva ("Digite o valor Y: ")
  leia (y)
  escreval (y)

  soma <- (x + y)
  escreval ("SOMA = ", soma)


fimalgoritmo