Algoritmo "senha_fixa"

// Autor(a): Daniel Pedroso
// Data: 01/04/2026

Var
// Seção de Declarações das variáveis
 senha : inteiro

Inicio
// Seção de Comandos
 escreva ("Digite a senha:  ")
 leia (senha)
 escreval (senha)
 
 enquanto senha <> 2002 faca 
   escreval ("Senha Invalida! Tente novamente: ", senha)
   leia (senha)
 fimenquanto
 
 se senha = 2002 entao
 
 escreval ("Acesso permitido!")
 
 fimse
  
 
 



fimalgoritmo