Algoritmo "teste_enquanto"

// Disciplina: Logica da programacao
// Autor(a): Daniel Pedroso
// Data: 28/03/2026

Var
// Seção de Declarações das variáveis
 x, soma : inteiro

Inicio
// Seção de Comandos
 escreva ("Digite o primeiro numero: ")
 leia (x)
 escreval (x)
 
 soma <- 0
 enquanto x <> 0 faca
    soma <- soma + x
    escreva ("Digite outro numero: ")
    leia (x)
 escreval (x)
 fimenquanto
 
 escreval ("SOMA = ", soma)


fimalgoritmo
